export const seznamKombinaci: Map<string, string> = new Map([
  
    ["air_air", "pressure"],
    ["air_cloud", "sky"],
    ["air_earth", "dust"],
    ["air_energy", "wind"],
    ["air_fire", "energy"],
    ["air_lava", "stone"],
    ["air_life", "bird"],
    ["air_metal", "rust"],
    ["air_pressure", "atmosphere"],
    ["air_steam", "cloud"],
    ["air_steel", "rust"],
    ["air_water", "rain"],
    ["air_wave", "sound"],
    ["alcohol_flower", "perfume"],
    ["alcohol_fruit", "wine"],
    ["alcohol_human", "drunk"],
    ["alcohol_rose", "perfume"],
    ["algae_stone", "moss"],
    ["angel_music", "harp"],
    ["armor_bullet", "bulletproof vest"],
    ["armor_human", "knight"],
    ["armor_life", "robot"],
    ["armor_wild_animal", "armadillo"],
    ["ash_oil", "soap"],
    ["atmosphere_meteoroid", "meteor"],
    ["axe_electricity", "chainsaw"],
    ["axe_human", "lumberjack"],
    ["bacon_bread", "sandwich"],
    ["bacteria_glass", "microscope"],
    ["bacteria_glasses", "microscope"],
    ["bacteria_human", "sickness"],
    ["bacteria_milk", "yogurt"],
    ["baker_house", "bakery"],
    ["beach_glasses", "sunglasses"],
    ["beach_sand", "beach"],
    ["beach_sandwich", "picnic"],
    ["beach_tree", "palm"],
    ["beaver_duck", "platypus"],
    ["beaver_river", "dam"],
    ["beaver_tree", "dam"],
    ["beaver_wood", "dam"],
    ["bee_beehive", "honey"],
    ["bee_flower", "honey"],
    ["bee_house", "beehive"],
    ["bee_tree", "beehive"],
    ["beer_human", "drunk"],
    ["bird_bird", "egg"],
    ["bird_city", "pigeon"],
    ["bird_clock", "cuckoo"],
    ["bird_corpse", "vulture"],
    ["bird_dinosaur", "pterodactyl"],
    ["bird_earth", "ostrich"],
    ["bird_field", "crow"],
    ["bird_fire", "phoenix"],
    ["bird_flower", "hummingbird"],
    ["bird_horse", "pegasus"],
    ["bird_human", "angel"],
    ["bird_lake", "duck"],
    ["bird_letter", "pigeon"],
    ["bird_mountain", "eagle"],
    ["bird_night", "owl"],
    ["bird_ocean", "seagull"],
    ["bird_paper", "origami"],
    ["bird_pond", "duck"],
    ["bird_sand", "ostrich"],
    ["bird_scarecrow", "crow"],
    ["bird_sea", "seagull"],
    ["bird_statue", "pigeon"],
    ["bird_unicorn", "pegasus"],
    ["bird_water", "duck"],
    ["bird_wizard", "owl"],
    ["blade_blade", "scissors"],
    ["blade_cow", "leather"],
    ["blade_doctor", "scalpel"],
    ["blade_electricity", "blender"],
    ["blade_fire", "flamethrower"],
    ["blade_glass", "blender"],
    ["blade_grass", "scythe"],
    ["blade_hospital", "scalpel"],
    ["blade_human", "blood"],
    ["blade_pig", "leather"],
    ["blade_pumpkin", "jack-o'-lantern"],
    ["blade_star", "shuriken"],
    ["blade_steel", "sword"],
    ["blade_wheat", "scythe"],
    ["blade_wood", "axe"],
    ["blood_fabric", "bandage"],
    ["blood_fish", "piranha"],
    ["blood_human", "vampire"],
    ["blood_ocean", "shark"],
    ["blood_sea", "shark"],
    ["boat_fabric", "sailboat"],
    ["boat_human", "sailor"],
    ["boat_pirate", "pirate ship"],
    ["boat_wind", "sailboat"],
    ["bone_bone", "skeleton"],
    ["bone_chicken", "chicken wing"],
    ["bone_light", "x-ray"],
    ["book_house", "library"],
    ["bread_cheese", "sandwich"],
    ["bread_fire", "toast"],
    ["bread_ham", "sandwich"],
    ["bread_meat", "hamburger"],
    ["brick_campfire", "fireplace"],
    ["brick_fireplace", "chimney"],
    ["brick_smoke", "chimney"],
    ["broom_electricity", "vacuum cleaner"],
    ["broom_human", "witch"],
    ["broom_wizard", "witch"],
    ["campfire_fabric", "smoke signal"],
    ["campfire_house", "fireplace"],
    ["campfire_sugar", "marshmallows"],
    ["campfire_wall", "fireplace"],
    ["campfire_witch", "cauldron"],
    ["candle_pumpkin", "jack-o'-lantern"],
    ["car_electricity", "electric car"],
    ["car_fireman", "firetruck"],
    ["car_gun", "tank"],
    ["carbon_dioxide_fire", "fire extinguisher"],
    ["carbon_dioxide_metal", "fire extinguisher"],
    ["carbon_dioxide_pressure", "fire extinguisher"],
    ["carbon_dioxide_juice", "soda"],
    ["carbon_dioxide_water", "soda"],
    ["carrot_snow", "snowman"],
    ["carrot_snowball", "snowman"],
    ["carrot_wild_animal", "rabbit"],
    ["cart_horse", "wagon"],
    ["castle_human", "monarch"],
    ["castle_sand", "sand castle"],
    ["cat_wild_animal", "lion"],
    ["chain_metal", "chain"],
    ["chain_steel", "chain"],
    ["charcoal_wood", "pencil"],
    ["cheese_dough", "pizza"],
    ["chicken_water", "chicken soup"],
    ["christmas_tree_human", "santa"],
    ["christmas_tree_sugar", "candy cane"],
    ["clay_fire", "brick"],
    ["clay_life", "golem"],
    ["clay_sun", "brick"],
    ["clock_sun", "sundial"],
    ["cloud_earth", "fog"],
    ["cloud_energy", "storm"],
    ["coal_metal", "steel"],
    ["coal_pressure", "diamond"],
    ["coal_wood", "pencil"],
    ["cold_electricity", "fridge"],
    ["cold_metal", "fridge"],
    ["cold_steam", "snow"],
    ["cold_tea", "iced tea"],
    ["computer_computer", "internet"],
    ["computer_mouse", "computer mouse"],
    ["computer_web", "internet"],
    ["computer_wire", "internet"],
    ["cookie_santa", "gift"],
    ["corpse_earth", "grave"],
    ["corpse_electricity", "frankenstein"],
    ["corpse_life", "zombie"],
    ["corpse_pyramid", "mummy"],
    ["corpse_time", "bone"],
    ["corpse_wood", "coffin"],
    ["cotton_fabric", "pillow"],
    ["cow_farmer", "milk"],
    ["cow_fire", "steak"],
    ["cow_human", "milk"],
    ["cow_rope", "lasso"],
    ["cyclist_bicycle", "cyclist"],
    ["desert_grave", "pyramid"],
    ["desert_plant", "cactus"],
    ["desert_stone", "pyramid"],
    ["desert_water", "oasis"],
    ["diamond_gold", "ring"],
    ["diamond_metal", "ring"],
    ["dinosaur_earth", "fossil"],
    ["dinosaur_meat", "tyrannosaurus rex"],
    ["dinosaur_stone", "fossil"],
    ["dinosaur_time", "fossil"],
    ["doctor_mold", "penicillin"],
    ["doctor_tool", "stethoscope"],
    ["dog_forest", "wolf"],
    ["dog_house", "doghouse"],
    ["dog_sea", "seal"],
    ["dog_wild_animal", "wolf"],
    ["dough_fire", "bread"],
    ["dough_fruit", "pie"],
    ["dough_life", "gingerbread man"],
    ["dough_oil", "donut"],
    ["dough_sugar", "cookie"],
    ["dragon_knight", "hero"],
    ["drunk_human", "drunk"],
    ["dust_fire", "gunpowder"],
    ["earth_earth", "pressure"],
    ["earth_earthquake", "mountain"],
    ["earth_fire", "lava"],
    ["earth_life", "human"],
    ["earth_plant", "grass"],
    ["earth_rain", "plant"],
    ["earth_sky", "horizon"],
    ["earth_space", "planet"],
    ["earth_water", "mud"],
    ["earthquake_ocean", "tsunami"],
    ["earthquake_sea", "tsunami"],
    ["eagle_mountain", "eagle"],
    ["egg_hay", "nest"],
    ["egg_livestock", "chicken"],
    ["egg_sand", "turtle"],
    ["egg_sky", "bird"],
    ["electric_car", "electric car"],
    ["electricity_fish", "electric eel"],
    ["electricity_flashlight", "light"],
    ["electricity_glass", "light bulb"],
    ["electricity_gun", "taser"],
    ["electricity_human", "electrician"],
    ["electricity_light_bulb", "light"],
    ["electricity_metal", "wire"],
    ["electricity_nerd", "computer"],
    ["electricity_needle", "sewing machine"],
    ["electricity_windmill", "wind turbine"],
    ["electricity_zombie", "frankenstein"],
    ["energy_fruit", "sugar"],
    ["energy_juice", "sugar"],
    ["energy_metal", "electricity"],
    ["energy_milk", "butter"],
    ["energy_sand", "sandstorm"],
    ["energy_swamp", "life"],
    ["energy_volcano", "ash"],
    ["engineer_glasses", "safety glasses"],
    ["engineer_paper", "blueprint"],
    ["excalibur_human", "monarch"],
    ["explosion_metal", "grenade"],
    ["explosion_sky", "fireworks"], //KONEC KONEC KONEC KOENCEKNSKDFKLSADFJLSAJFLSAKJDFLKSADJFLSAJDFLSAJL https://game-icons.net/1x1/lorc/firework-rocket.html#download https://www.flaticon.com/search?word=platypus&color=color&shape=outline
    ["explosion_star", "super nova"],
    ["fabric_hero", "cape"],
    ["fabric_pilot", "parachute"],
    ["fabric_rain", "umbrella"],
    ["fabric_smoke", "smoke signal"],
    ["fabric_wood", "tent"],
    ["family_tree", "family tree"],
    ["farmer_field", "wheat"],
    ["farmer_grass", "hay"],
    ["farmer_house", "farm"],
    ["farmer_life", "livestock"],
    ["farmer_plant", "wheat"],
    ["farmer_wild_animal", "livestock"],
    ["faun_goat", "faun"],
    ["fence_leaf", "hedge"],
    ["fence_plant", "hedge"],
    ["field_fruit", "vegetable"],
    ["field_human", "farmer"],
    ["fire_campfire", "campfire"],
    ["fire_fabric", "smoke signal"],
    ["fire_human", "fireman"],
    ["fire_juice", "sugar"],
    ["fire_oil", "oil lamp"],
    ["fire_plant", "tobacco"],
    ["fire_pumpkin", "jack-o'-lantern"],
    ["fire_sandwich", "toast"],
    ["fire_sky", "sun"],
    ["fire_vegetable", "pumpkin"],
    ["fire_water", "steam"],
    ["fire_wood", "campfire"],
    ["fire_world", "volcano"],
    ["fish_horse", "seahorse"],
    ["fish_seaweed", "sushi"],
    ["fish_sword", "swordfish"],
    ["fishing_rod_human", "angler"],
    ["flamethrower_snowman", "puddle"],
    ["flower_flower", "garden"],
    ["flower_love", "rose"],
    ["flower_pond", "water lilly"],
    ["flower_steam", "perfume"],
    ["flower_water", "perfume"],
    ["flower_wild_animal", "butterfly"],
    ["flute_human", "music"],
    ["fog_smoke", "smog"],
    ["forest_life", "wild animal"],
    ["fruit_palm", "coconut"],
    ["fruit_pressure", "juice"],
    ["fruit_tree", "fruit tree"],
    ["fruit_water", "lemonade"],
    ["garden_human", "gardener"],
    ["garden_plant", "flower"],
    ["garden_statue", "gnome"],
    ["garden_water", "pond"],
    ["glass_fire", "glass"],
    ["glass_house", "window"],
    ["glass_metal", "mirror"],
    ["glass_oil", "oil lamp"],
    ["glass_plant", "greenhouse"],
    ["glass_rainbow", "prism"],
    ["glass_sand", "hourglass"],
    ["glass_sky", "telescope"],
    ["glass_snow", "snow globe"],
    ["glass_space", "telescope"],
    ["glass_star", "telescope"],
    ["glasses_human", "nerd"],
    ["glasses_snow", "ski goggles"],
    ["glasses_sun", "sunglasses"],
    ["glasses_water", "swim goggles"],
    ["gold_metal", "safe"],
    ["gold_monarch", "crown"],
    ["gold_paper", "money"],
    ["gold_steel", "safe"],
    ["grape_pressure", "wine"],
    ["grass_mud", "swamp"],
    ["grass_sandwich", "picnic"],
    ["grass_scythe", "hay"],
    ["grass_sun", "hay"],
    ["grass_wild_animal", "ant"],
    ["grave_stone", "gravestone"],
    ["graveyard_graveyard", "graveyard"],
    ["greenhouse_plant", "greenhouse"],
    ["grim_reaper_human", "corpse"],
    ["gun_human", "corpse"],
    ["gunpowder_metal", "bullet"],
    ["gunpowder_pirate_ship", "cannon"],
    ["gunpowder_wire", "dynamite"],
    ["hail_ice", "hail"],
    ["hay_hay", "hay bale"],
    ["hay_human", "scarecrow"],
    ["hay_livestock", "horse"],
    ["hay_wood", "broom"],
    ["hero_fabric", "cape"],
    ["ice_cream_car", "ice cream truck"],
    ["ice_cream_milk", "milk shake"],
    ["ice_dog", "husky"],
    ["ice_energy", "avalanche"],
    ["ice_human", "snowman"],
    ["ice_ocean", "iceberg"],
    ["ice_sea", "iceberg"],
    ["ice_wild_animal", "penguin"],
    ["internet_email", "email"],
    ["island_volcano", "isle"],
    ["juice_sugar", "jam"],
    ["knight_castle", "castle"],
    ["lake_dam", "lake"],
    ["lamp_lava", "lava lamp"],
    ["leather_horse", "saddle"],
    ["life_clay", "golem"],
    ["life_dough", "gingerbread man"],
    ["life_swamp", "bacteria"],
    ["light_glass", "light bulb"],
    ["light_water", "optical fiber"],
    ["lightning_rod_metal", "electricity"],
    ["lion_human", "sphinx"],
    ["livestock_mountain", "goat"],
    ["livestock_mud", "pig"],
    ["lumberjack_wood", "log cabin"],
    ["magnet_sand", "steel wool"],
    ["map_pirate", "treasure map"],
    ["meat_bread", "hamburger"],
    ["meat_fire", "bacon"],
    ["mercury_planet", "mercury"],
    ["metal_energy", "electricity"],
    ["metal_pirate", "cannon"],
    ["meteor_earth", "meteorite"],
    ["milk_ice", "ice cream"],
    ["milk_pressure", "butter"],
    ["moon_human", "astronaut"],
    ["moss_stone", "moss"],
    ["mountain_goat", "mountain goat"],
    ["mountain_range", "mountain range"],
    ["mud_plant", "swamp"],
    ["music_paper", "sheet music"],
    ["needle_thread", "sewing machine"],
    ["nerd_glasses", "nerd"],
    ["oil_vegetable", "French fries"],
    ["oxygen_plant", "carbon dioxide"],
    ["paint_rainbow", "paint"],
    ["paper_pencil", "letter"],
    ["pasta_cheese", "mac and cheese"],
    ["pegasus_rainbow", "unicorn"],
    ["pencil_wood", "pencil"],
    ["petroleum_time", "plastic"],
    ["phoenix_fire", "phoenix"],
    ["pilot_airplane", "pilot"],
    ["pirate_ship", "pirate ship"],
    ["plant_clay", "bonsai tree"],
    ["plant_glass", "greenhouse"],
    ["plant_night", "carbon dioxide"],
    ["plant_pressure", "oil"],
    ["plant_sun", "sunflower"],
    ["plant_time", "tree"],
    ["plant_wall", "ivy"],
    ["pottery_clay", "pottery"],
    ["pressure_air", "atmosphere"],
    ["pressure_earth", "coal"],
    ["pressure_plant", "oil"],
    ["prism_light", "rainbow"],
    ["rain_energy", "storm"],
    ["rain_plant", "flower"],
    ["rain_snow", "blizzard"],
    ["rainbow_rainbow", "double rainbow!"],
    ["robot_vacuum", "roomba"],
    ["rocket_human", "astronaut"],
    ["rope_wood", "fishing rod"],
    ["rose_love", "rose"],
    ["sailboat_pirate", "pirate ship"],
    ["sand_cactus", "desert"],
    ["sand_witch", "hourglass"],
    ["sandpaper_wood", "smooth"],
    ["scissors_wool", "sweater"],
    ["sea_earth", "horizon"],
    ["sea_moon", "tide"],
    ["sea_sun", "salt"],
    ["seagull_beach", "seagull"],
    ["sewing_machine_fabric", "clothes"],
    ["sickness_sea", "seasickness"],
    ["sky_energy", "aurora"],
    ["sky_fire", "sun"],
    ["sky_star", "space"],
    ["smoke_fog", "smog"],
    ["snow_energy", "avalanche"],
    ["snow_human", "snowman"],
    ["snow_mobile", "snowmobile"],
    ["snow_storm", "blizzard"],
    ["solar_cell_sun", "electricity"],
    ["sound_human", "music"],
    ["space_house", "space station"],
    ["space_life", "alien"],
    ["star_cluster", "galaxy"],
    ["star_night", "constellation"],
    ["steam_boiler", "steam engine"],
    ["steam_metal", "boiler"],
    ["stone_tool", "axe"],
    ["storm_sand", "sandstorm"],
    ["sugar_egg", "meringue"],
    ["sun_plant", "cactus"],
    ["sun_snowman", "carrot"],
    ["sun_vegetable", "carrot"],
    ["sunflower_oil", "oil"],
    ["swamp_energy", "life"],
    ["swamp_wild_animal", "lizard"],
    ["sweater_wool", "sweater"],
    ["sword_stone", "excalibur"],
    ["telescope_sky", "telescope"],
    ["time_bread", "mold"],
    ["time_corpse", "skeleton"],
    ["time_fossil", "petroleum"],
    ["time_fruit", "alcohol"],
    ["time_juice", "vinegar"],
    ["tool_metal", "armor"],
    ["tool_needle", "sewing machine"],
    ["tool_wheat", "flour"],
    ["tree_house", "treehouse"],
    ["tree_light", "christmas tree"],
    ["tree_lumberjack", "wood"],
    ["tree_woodpecker", "wood"],
    ["turtle_ninja", "ninja turtle"],
    ["unicorn_rainbow", "pegasus"],
    ["vampire_sun", "dust"],
    ["vegetable_oil", "French fries"],
    ["volcano_ring", "the one ring"],
    ["water_clay", "mud"],
    ["water_electricity", "hydrogen"],
    ["water_glass", "aquarium"],
    ["water_plant", "algae"],
    ["water_sand", "beach"],
    ["wheel_energy", "steam engine"],
    ["wheel_water", "waterwheel"],
    ["wild_animal_forest", "squirrel"],
    ["wind_boat", "sailboat"],
    ["wind_turbine", "wind turbine"],
    ["wine_time", "vinegar"],
    ["wire_light", "optical fiber"],
    ["wizard_broom", "witch"],
    ["wood_beam", "log cabin"],
    ["wood_fire", "charcoal"],
    ["wood_tool", "wheel"],
    ["wool_sheep", "wool"],
]);