export const seznamKombinaci: Map<string, string> = new Map([

    ["Pták_Ocel", "Letadlo"],
    ["Pták_Kov", "Letadlo"],
    ["Hodiny_Zvuk", "Budík"],   
    ["Ovoce_Čas", "Alkohol"],
    ["Džus_Čas", "Alkohol"],
    ["Voda_Rostlina", "Řasy"],
    ["Moře_Rostlina", "Řasy"],
    ["Oceán_Rostlina", "Řasy"],
    ["Život_Vesmír", "Mimozemšťan"],
    ["Ještěrka_Bažina", "Aligátor"],
    ["Ještěrka_Řeka", "Aligátor"],
    ["Auto_Nemocnice", "Sanitka"],
    ["Auto_Doktor", "Sanitka"],
    ["Člověk_Pták", "Anděl"],
    ["Člověk_Prut", "Rybář"],
    ["Tráva_Divoké zvíře", "Mravenec"],
    ["Divoké zvíře_Cukr", "Mravenec"],
    ["Brnění_Divoké zvíře", "Pásovec"],
    ["Kov_Nástroj", "Brnění"],
    ["Ocel_Nástroj", "Brnění"],
    ["Energie_Sopka", "Popel"],
    ["Měsíc_Člověk", "Astronaut"],
    ["Člověk_Raketa", "Astronaut"],
    ["Vesmírná stanice_Člověk", "Astronaut"],
    ["Vesmír_Člověk", "Astronaut"],
    ["Tlak_Vzduch", "Atmosféra"],
    ["Tlak_Obloha", "Atmosféra"],
    ["Exploze_Energie", "Atomová bomba"],
    ["Sníh_Energie", "Lavina"],
    ["Dřevo_Čepel", "Sekera"],
    ["Oheň_Prase", "Slanina"],
    ["Život_Bažina", "Bakterie"],
    ["Mouka_Člověk", "Pekař"],
    ["Chléb_Člověk", "Pekař"],
    ["Těsto_Člověk", "Pekař"],
    ["Pekař_Dům", "Pekařství"],
    ["Chléb_Dům", "Pekařství"],
    ["Opice_Ovoce", "Banán"],
    ["Tkanina_Krev", "Bandáž"],
    ["Peníze_Dům", "Banka"],
    ["Zlato_Dům", "Banka"],
    ["Sejf_Dům", "Banka"],
    ["Dům_Kráva", "Stodola"],
    ["Dům_Hospodářské zvíře", "Stodola"],
    ["Seno_Dům", "Stodola"],
    ["Pták_Myš", "Netopýr"],
    ["Obloha_Myš", "Netopýr"],
    ["Čepel_Zbraň", "Bajonet"],
    ["Meč_Zbraň", "Bajonet"],
    ["Písek_Moře", "Pláž"],
    ["Písek_Oceán", "Pláž"],
    ["Dřevo_Divoké zvíře", "Bobr"],
    ["Přehrada_Divoké zvíře", "Bobr"],
    ["Divoké zvíře_Květina", "Včela"],
    ["Dům_Včela", "Úl"],
    ["Strom_Včela", "Úl"],
    ["Pšenice_Alkohol", "Pivo"],
    ["Vzduch_Život", "Pták"],
    ["Život_Obloha", "Pták"],
    ["Vajíčko_Vzduch", "Pták"],
    ["Vajíčko_Obloha", "Pták"],
    ["Pták_Dům", "Ptačí budka"],
    ["Hvězda_Tlak", "Černá díra"],
    ["Kov_Kámen", "Čepel"],
    ["Sklo_Čepel", "Mixér"],
    ["Čepel_Elektřina", "Mixér"],
    ["Sníh_Sníh", "Sněhová bouře"],
    ["Bouře_Sníh", "Sněhová bouře"],
    ["Vítr_Sníh", "Sněhová bouře"],
    ["Čepel_Člověk", "Krev"],
    ["Papír_Inženýr", "Plán"],
    ["Dřevo_Voda", "Loď"],
    ["Kov_Pára", "Bojler"],
    ["Čas_Mrtvola", "Kost"],
    ["Keramika_Strom", "Bonsaj"],
    ["Nůžky_Strom", "Bonsaj"],
    ["Dřevo_Papír", "Kniha"],
    ["Příběh_Papír", "Kniha"],
    ["Oheň_Těsto", "Chléb"],
    ["Oheň_Hlína", "Cihla"],
    ["Oheň_Bláto", "Cihla"],
    ["Slunce_Bláto", "Cihla"],
    ["Slunce_Hlína", "Cihla"],
    ["Dřevo_Řeka", "Most"],
    ["Kov_Řeka", "Most"],
    ["Ocel_Řeka", "Most"],
    ["Seno_Dřevo", "Koště"],
    ["Kov_Střelný prach", "Kulka"],
    ["Brnění_Kulka", "Neprůstřelná vesta"],
    ["Člověk_Maso", "Řezník"],
    ["Energie_Mléko", "Máslo"],
    ["Mléko_Tlak", "Máslo"],
    ["Květina_Divoké zvíře", "Motýl"],
    ["Poušť_Rostlina", "Kaktus"],
    ["Písek_Rostlina", "Kaktus"],
    ["Těsto_Svíčka", "Dort"],
    ["Poušť_Divoké zvíře", "Velbloud"],
    ["Poušť_Kůň", "Velbloud"],
    ["Hospodářské zvíře_Poušť", "Velbloud"],
    ["Oheň_Dřevo", "Táborák"],
    ["Vosk_Vlákno", "Svíčka"],   //VOSKKKK
    ["Vosk_Oheň", "Svíčka"],
    ["Cukr_Vánoční stromeček", "Cukrová hůl"],
    ["Střelný prach_Pirátská loď", "Kanon"],
    ["Střelný prach_Hrad", "Kanon"],
    ["Hrdina_Tkanina", "Kápě"],
    ["Kolo_Kov", "Auto"],
    ["Člověk_Kyslík", "Oxid uhličitý"],
    ["Rostlina_Noc", "Oxid uhličitý"],
    ["Strom_Noc", "Oxid uhličitý"],
    ["Sněhulák_Zelenina", "Mrkev"],
    ["Slunce_Sněhulák", "Mrkev"],
    ["Kolo_Dřevo", "Vozík"],
    ["Dům_Rytíř", "Hrad"],
    ["Divoké zvíře_Mléko", "Kočka"],
    ["Kočka_Rostlina", "Šanta kočičí"],
    ["Kov_Čarodějnice", "Kotel"],
    ["Ocel_Čarodějnice", "Kotel"],
    ["Krb_Čarodějnice", "Kotel"],
    ["Táborák_Čarodějnice", "Kotel"],
    ["Jikry_Člověk", "Kaviár"],
    ["Kůň_Člověk", "Kentaur"],
    ["Kov_Provaz", "Řetěz"],
    ["Ocel_Provaz", "Řetěz"],
    ["Sekera_Elektřina", "Motorová pila"],
    ["Ještěrka_Duha", "Chameleon"],
    ["Oheň_Dřevo", "Dřevěné uhlí"],
    ["Čas_Mléko", "Sýr"],
    ["Vajíčko_Hospodářské zvíře", "Slepice"],
    ["Hospodářské zvíře_Pták", "Slepice"],
    ["Pták_Farmář", "Slepice"],
    ["Voda_Slepice", "Kuřecí polévka"],
    ["Slepice_Kost", "Kuřecí stehno"],
    ["Dům_Krb", "Komín"],
    ["Kouř_Cihla", "Komín"],
    ["Krb_Cihla", "Komín"],
    ["Žárovka_Strom", "Vánoční stromeček"],
    ["Strom_Hvězda", "Vánoční stromeček"],
    ["Tabák_Papír", "Cigareta"],
    ["Vesnice_Vesnice", "Město"],
    ["Písek_Bláto", "Hlína"],
    ["Čas_Nástroj", "Hodiny"],
    ["Čas_Kolo", "Hodiny"],
    ["Čas_Elektřina", "Hodiny"],
    ["Vzduch_Pára", "Mrak"],
    ["Tlak_Rostlina", "Uhlí"],
    ["Slunce_Sněhulák", "Uhlí"],
    ["Palma_Ovoce", "Kokos"],
    ["Kokos_Nástroj", "Kokosové mléko"],
    ["Mléko_Kokos", "Kokosové mléko"],
    ["Dřevo_Mrtvola", "Rakev"],
    ["Člověk_Déšť", "Chlad"],
    ["Elektřina_Nerd", "Počítač"],
    ["Drát_Nerd", "Počítač"],
    ["Nástroj_Nerd", "Počítač"],
    ["Myš_Počítač", "Počítačová myš"],
    ["Kniha_Recept", "Kuchařka"],
    ["Recept_Recept", "Kuchařka"],
    ["Těsto_Cukr", "Sušenka"],
    ["Člověk_Zbraň", "Mrtvola"],
    ["Člověk_Smrtka", "Mrtvola"],
    ["Rostlina_Mrak", "Bavlna"],
    ["Tráva_Hospodářské zvíře", "Kráva"],
    ["Pták_Strašák", "Vrána"],
    ["Pták_Pole", "Vrána"],
    ["Zlato_Monarcha", "Koruna"],
    ["Kov_Monarcha", "Koruna"],
    ["Čarodějnice_Sklo", "Krystalová koule"],
    ["Čaroděj_Sklo", "Krystalová koule"],
    ["Hodiny_Pták", "Kukačky"],
    ["Člověk_Robot", "Kyborg"],
    ["Horské kolo_Člověk", "Cyklista"],
    ["Bobr_Řeka", "Přehrada"],
    ["Bobr_Strom", "Přehrada"],
    ["Bobr_Dřevo", "Přehrada"],
    ["Zeď_Řeka", "Přehrada"],
    ["Slunce_Čas", "Den"],
    ["Noc_Slunce", "Den"],
    ["Čas_Noc", "Den"],
    ["Obloha_Slunce", "Den"],
    ["Písek_Písek", "Poušť"],
    ["Kaktus_Písek", "Poušť"],
    ["Uhlí_Tlak", "Diamant"],
    ["Čas_Ještěrka", "Dinosaurus"],
    ["Nemocnice_Člověk", "Doktor"],
    ["Člověk_Divoké zvíře", "Pes"],
    ["Dům_Pes", "Psí bouda"],
    ["Dům_Dům", "Vesnice"],
    ["Olej_Těsto", "Donut"],
    ["Mouka_Voda", "Těsto"],
    ["Ještěrka_Oheň", "Drak"],
    ["Letadlo_Robot", "Dron"],
    ["Dřevo_Kůže", "Buben"],
    ["Člověk_Alkohol", "Opilec"],
    ["Pivo_Člověk", "Opilec"],
    ["Člověk_Víno", "Opilec"],
    ["Oxid uhličitý_Chlad", "Suchý led"],
    ["Led_Oxid uhličitý", "Suchý led"],
    ["Pták_Jezero", "Kachna"],
    ["Voda_Pták", "Kachna"],
    ["Pták_Rybník", "Kachna"],
    ["Čas_House", "Kachna"],
    ["Vajíčko_Kachna", "House"],
    ["Písek_Vítr", "Duny"],
    ["Poušť_Vítr", "Duny"],
    ["Pláž_Vítr", "Duny"],
    ["Země_Vzduch", "Prach"],
    ["Slunce_Upír", "Prach"],
    ["Den_Upír", "Prach"],
    ["Střelný prach_Drát", "Dynamit"],
    ["Hora_Pták", "Orel"],
    ["Země_Energie", "Zemětřesení"],
    ["Země_Vlna", "Zemětřesení"],
    ["Slunce_Měsíc", "Zatmění"],
    ["Život_Kámen", "Vajíčko"],
    ["Pták_Pták", "Vajíčko"],
    ["Ještěrka_Ještěrka", "Vajíčko"],
    ["Elektřina_Auto", "Elektrické auto"],
    ["Elektřina_Ryba", "Elektrický úhoř"],
    ["Elektřina_Člověk", "Elektrikář"],
    ["Drát_Člověk", "Elektrikář"],
    ["Energie_Kov", "Elektřina"],
    ["Vítr_Větrná turbína", "Elektřina"],
    ["Počítač_Dopis", "Email"],
    ["Internet_Dopis", "Email"],
    ["Oheň_Vzduch", "Energie"],
    ["Slunce_Rostlina", "Energie"],
    ["Nástroj_Člověk", "Inženýr"],
    ["Energie_Sopka", "Erupce"],
    ["Kámen_Meč", "Exkalibr"],
    ["Oheň_Střelný prach", "Exploze"],
    ["Nástroj_Vlákno", "Tkanina"],
    ["Dům_Člověk", "Rodina"],
    ["Dům_Farmář", "Farma"],
    ["Stodola_Farmář", "Farma"],
    ["Rostlina_Člověk", "Farmář"],
    ["Člověk_Pole", "Farmář"],
    ["Vidle_Člověk", "Farmář"],
    ["Dřevo_Zeď", "Plot"],
    ["Farmář_Země", "Pole"],
    ["Nástroj_Země", "Pole"],
    ["Oxid uhličitý_Oheň", "Hasící přístroj"],
    ["Oxid uhličitý_Tlak", "Hasící přístroj"],
    ["Oxid uhličitý_Kov", "Hasící přístroj"],
    ["Oheň_Člověk", "Hasič"],
    ["Táborák_Dům", "Krb"],
    ["Cihla_Táborák", "Krb"],
    ["Zeď_Táborák", "Krb"],
    ["Obloha_Exploze", "Ohňostroj"],
    ["Čas_Jikry", "Ryba"],
    ["Ryba_Nástroj", "Prut"],
    ["Ryba_Dřevo", "Prut"],
    ["Zbraň_Oheň", "Plamenomet"],
    ["Světlo_Nástroj", "Baterka"],
    ["Déšť_Čas", "Potopa"],
    ["Pšenice_Kámen", "Mouka"],
    ["Mlýn_Pšenice", "Mouka"],
    ["Rostlina_Zahrada", "Květina"],
    ["Dřevo_Vítr", "Flétna"],
    ["Ryba_Pták", "Létající ryba"],
    ["Obloha_Ryba", "Létající ryba"],
    ["Země_Mrak", "Mlha"],
    ["Strom_Strom", "Les"],
    ["Čas_Dinosaurus", "Fosilie"],
    ["Země_Dinosaurus", "Fosilie"],
    ["Dinosaurus_Kámen", "Fosilie"],
    ["Voda_Socha", "Fontána"],
    ["Divoké zvíře_Slepice", "Liška"],
    ["Elektřina_Zombie", "Frankenstein"],
    ["Mrtvola_Elektřina", "Frankenstein"],
    ["Zelenina_Olej", "Hranolky"],
    ["Chlad_Kov", "Lednice"],
    ["Chlad_Elektřina", "Lednice"],
    ["Led_Kov", "Lednice"],
    ["Rybník_Divoké zvíře", "Žába"],
    ["Farmář_Strom", "Ovoce"],
    ["Strom_Slunce", "Ovoce"],
    ["Strom_Ovoce", "Ovocný strom"],
    ["Rostlina_Rostlina", "Zahrada"],
    ["Rostlina_Tráva", "Zahrada"],
    ["Dům_Tráva", "Zahrada"],
    ["Člověk_Zahrada", "Zahradník"],
    ["Hřbitov_Noc", "Duch"],
    ["Hrad_Noc", "Duch"],
    ["Santa_Vánoční stromeček", "Dárek"],
    ["Santa_Sušenka", "Dárek"],
    ["Santa_Komín", "Dárek"],
    ["Santa_Krb", "Dárek"],
    ["Život_Těsto", "Perníček"],
    ["Led_Hora", "Ledovec"],
    ["Oheň_Písek", "Sklo"],
    ["Písek_Elektřina", "Sklo"],
    ["Sklo_Kov", "Dioptrické brýle"],
    ["Sklo_Sklo", "Dioptrické brýle"],
    ["Socha_Zahrada", "Gnom"],
    ["Hora_Hospodářské zvíře", "Koza"],
    ["Slunce_Kov", "Zlato"],
    ["Duha_Kov", "Zlato"],
    ["Život_Hlína", "Golem"],
    ["Tlak_Láva", "Granit"],
    ["Země_Rostlina", "Tráva"],
    ["Země_Rakev", "Hrob"],
    ["Země_Mrtvola", "Hrob"],
    ["Kámen_Hrob", "Hrob"],
    ["Hrob_Hrob", "Hřbitov"],
    ["Sklo_Rostlina", "Skleník"],
    ["Exploze_Kov", "Granát"],
    ["Člověk_Kosa", "Smrtka"],
    ["Mrtvola_Kosa", "Smrtka"],
    ["Kov_Kulka", "Zbraň"],
    ["Oheň_Prach", "Střelný prach"],
    ["Déšť_Led", "Kroupy"],
    ["Led_Bouře", "Kroupy"],
    ["Led_Mrak", "Kroupy"],
    ["Maso_Kouř", "Šunka"],
    ["Maso_Chléb", "Hamburger"],
    ["Kov_Dřevo", "Kladivo"],
    ["Kolo_Myš", "Křeček"],
    ["Vajíčko_Voda", "Jikry"],
    ["Vajíčko_Moře", "Jikry"],
    ["Vajíčko_Oceán", "Jikry"],
    ["Vajíčko_Rybník", "Jikry"],
    ["Ryba_Ryba", "Jikry"],
    ["Hudba_Anděl", "Harfa"],
    ["Tráva_Farmář", "Seno"],
    ["Kosa_Tráva", "Seno"],
    ["Slunce_Tráva", "Seno"],
    ["Rostlina_Plot", "Ježek"],
    ["List_Plot", "Ježek"],
    ["Čepel_Letadlo", "Helikoptéra"],
    ["Mlýn_Letadlo", "Helikoptéra"],
    ["Rostlina_Nemoc", "Bylinky"],
    ["Nemoc_List", "Bylinky"],
    ["Rytíř_Drak", "Hrdina"],
    ["Včela_Květina", "Med"],
    ["Včela_Úl", "Med"],
    ["Obloha_Země", "Horizont"],
    ["Moře_Obloha", "Horizont"],
    ["Oceán_Obloha", "Horizont"],
    ["Seno_Hospodářské zvíře", "Kůň"],
    ["Kov_Kůň", "Podkova"],
    ["Dům_Nemoc", "Nemocnice"],
    ["Dům_Sanitka", "Nemocnice"],
    ["Dům_Doktor", "Nemocnice"],
    ["Zeď_Zeď", "Dům"],
    ["Život_Země", "Člověk"],
    ["Květina_Pták", "Kolibřík"],
    ["Energie_Vítr", "Hurikán"],
    ["Chlad_Voda", "Led"],
    ["Led_Moře", "Ledovec"],
    ["Led_Oceán", "Ledovec"],
    ["Antarktida_Moře", "Ledovec"],
    ["Antarktida_Oceán", "Ledovec"],
    ["Poušť_Sníh", "Antarktida"],
    ["Poušť_Led", "Antarktida"],
    ["Led_Mléko", "Zmrzlina"],
    ["Čaj_Led", "Ledový čaj"],
    ["Čaj_Chlad", "Ledový čaj"],
    ["Žárovka_Člověk", "Nápad"],
    ["Nerd_Žárovka", "Nápad"],
    ["Led_Dům", "Iglú"],
    ["Sníh_Dům", "Iglú"],
    ["Počítač_Drát", "Internet"],
    ["Počítač_Pavučina", "Internet"],
    ["Oceán_Sopka", "Ostrov"],
    ["Sopka_Moře", "Ostrov"],
    ["Rostlina_Zeď", "Břečťan"],
    ["Dýně_Oheň", "Svítící dýně"],
    ["Čepel_Dýně", "Svítící dýně"],
    ["Dýně_Svíčka", "Svítící dýně"],
    ["Džus_Cukr", "Marmeláda"],
    ["Voda_Ovoce", "Džus"],
    ["Tlak_Ovoce", "Džus"],
    ["Vítr_Papír", "Létající drak"],
    ["Obloha_Papír", "Létající drak"],
    ["Člověk_Brnění", "Rytíř"],
    ["Voda_Rybník", "Jezero"],
    ["Řeka_Přehrada", "Jezero"],
    ["Kov_Žárovka", "Lampa"],
    ["Kráva_Provaz", "Laso"],
    ["Kůň_Provaz", "Laso"],
    ["Země_Oheň", "Láva"],
    ["Strom_Vítr", "List"],
    ["Kráva_Čepel", "Kůže"],
    ["Prase_Čepel", "Kůže"],
    ["Ovoce_Voda", "Limonáda"],
    ["Papír_Tužka", "Dopis"],
    ["Dům_Kniha", "Knihovna"],
    ["Bažina_Energie", "Život"],
    ["Láska_Čas", "Život"],
    ["Žárovka_Elektřina", "Světlo"],
    ["Elektřina_Baterka", "Světlo"],
    ["Elektřina_Sklo", "Žárovka"],
    ["Světlo_Dům", "Maják"],
    ["Světlo_Pláž", "Maják"],
    ["Světlo_Oceán", "Maják"],
    ["Světlo_Moře", "Maják"],
    ["Divoké zvíře_Kočka", "Lev"],
    ["Farmář_Život", "Hospodářské zvíře"],
    ["Divoké zvíře_Člověk", "Hospodářské zvíře"],
    ["Farmář_Divoké zvíře", "Hospodářské zvíře"],
    ["Vajíčko_Bažina", "Ještěrka"],
    ["Dřevo_Dům", "Srub"],
    ["Člověk_Člověk", "Láska"],
    ["Člověk_Sekera", "Dřevorubec"],
    ["Motorová pila_Člověk", "Dřevorubec"],
    ["Dopis_Člověk", "Pošťák"],
    ["Země_Papír", "Mapa"],
    ["Planeta_Rez", "Mars"],
    ["Táborák_Cukr", "Marshmallows"],
    ["Olej_Vajíčko", "Majonéza"],
    ["Nástroj_Kráva", "Maso"],
    ["Řezník_Hospodářské zvíře", "Maso"],
    ["Řezník_Kráva", "Maso"],
    ["Řezník_Prase", "Maso"],
    ["Nástroj_Prase", "Maso"],
    ["Hospodářské zvíře_Čepel", "Maso"],
    ["Had_Člověk", "Medúza"],
    ["Ryba_Člověk", "Mořská panna"],
    ["Kámen_Oheň", "Kov"],
    ["Atmosféra_Meteor", "Meteor"],
    ["Meteor_Obloha", "Meteor"],
    ["Vesmír_Kámen", "Meteor"],
    ["Bakterie_Sklo", "Mikroskop"],
    ["Dioptrické brýle_Bakterie", "Mikroskop"],
    ["Kráva_Farmář", "Mléko"],
    ["Člověk_Kráva", "Mléko"],
    ["Kráva_Člověk", "Minotaur"],
    ["Kov_Sklo", "Zrcadlo"],
    ["Chléb_Čas", "Plíseň"],
    ["Hrad_Člověk", "Monarcha"],
    ["Člověk_Exkalibr", "Monarcha"],
    ["Člověk_Koruna", "Monarcha"],
    ["Zlato_Papír", "Peníze"],
    ["Divoké zvíře_Strom", "Opice"],
    ["Sýr_Obloha", "Měsíc"],
    ["Kámen_Obloha", "Měsíc"],
    ["Kámen_Rostlina", "Mech"],
    ["Kámen_Řasy", "Mech"],
    ["Motýl_Měsíc", "Můra"],
    ["Motýl_Noc", "Můra"],
    ["Energie_Horské kolo", "Motorka"],
    ["Ocel_Horské kolo", "Motorka"],
    ["Země_Zemětřesení", "Hora"],
    ["Sýr_Divoké zvíře", "Myš"],
    ["Dřevo_Sýr", "Pastička"],
    ["Kov_Sýr", "Pastička"],
    ["Voda_Země", "Bláto"],
    ["Mrtvola_Pyramida", "Mumie"],
    ["Člověk_Flétna", "Hudba"],
    ["Člověk_Zvuk", "Hudba"],
    ["Kov_Vlákno", "Jehla"],
    ["Kov_Seno", "Jehla"],
    ["Člověk_Dioptrické brýle", "Nerd"],
    ["Pták_Strom", "Hnízdo"],
    ["Pták_Seno", "Hnízdo"],
    ["Vajíčko_Seno", "Hnízdo"],
    ["Papír_Papír", "Noviny"],
    ["Čas_Měsíc", "Noc"],
    ["Den_Čas", "Noc"],
    ["Měsíc_Obloha", "Noc"],
    ["Člověk_Šuriken", "Ninja"],
    ["Ninja_Želva", "Ninjasaurus"],
    ["Veverka_Strom", "Oříšek"],
    ["Veverka_Ovoce", "Oříšek"],
    ["Voda_Poušť", "Oáza"],
    ["Voda_Láva", "Obsidian"],
    ["Voda_Moře", "Oceán"],
    ["Slunečnice_Tlak", "Olej"],
    ["Hlína_Olej", "Lucerna"],
    ["Olej_Provaz", "Lucerna"],
    ["Sklo_Olej", "Lucerna"],
    ["Oheň_Olej", "Lucerna"],
    ["Vajíčko_Oheň", "Volské oko"],
    ["Ovocný strom_Ovocný strom", "Sad"],
    ["Ovocný strom_Pole", "Sad"],
    ["Papír_Pták", "Origami"],
    ["Země_Pták", "Pštros"],
    ["Písek_Pták", "Pštros"],
    ["Pták_Noc", "Sova"],
    ["Čaroděj_Pták", "Sova"],
    ["Slunce_Rostlina", "Kyslík"],
    ["Oxid uhličitý_Rostlina", "Kyslík"],
    ["Voda_Duha", "Barva"],
    ["Voda_Tužka", "Barva"],
    ["Ostrov_Strom", "Palma"],
    ["Strom_Pláž", "Palma"],
    ["Dřevo_Tlak", "Papír"],
    ["Pilot_Tkanina", "Padák"],
    ["Pilot_Deštník", "Padák"],
    ["Pták_Pirát", "Papoušek"],
    ["Mouka_Vajíčko", "Nudle"],
    ["Pták_Kůň", "Pegas"],
    ["Obloha_Kůň", "Pegas"],
    ["Pták_Jednorožec", "Pegas"],
    ["Dřevo_Uhlí", "Tužka"],
    ["Dřevo_Dřevěné uhlí", "Tužka"],
    ["Led_Divoké zvíře", "Tučňák"],
    ["Led_Pták", "Tučňák"],
    ["Pták_Sníh", "Tučňák"],
    ["Doktor_Plíseň", "Penicilin"],
    ["Voda_Růže", "Parfém"],
    ["Voda_Květina", "Parfém"],
    ["Pára_Růže", "Parfém"],
    ["Pára_Květina", "Parfém"],
    ["Alkohol_Růže", "Parfém"],
    ["Alkohol_Květina", "Parfém"],
    ["Fosilie_Čas", "Ropa"],
    ["Fosilie_Tlak", "Ropa"],
    ["Oheň_Pták", "Fénix"],
    ["Tráva_Sendvič", "Piknik"],
    ["Pláž_Sendvič", "Piknik"],
    ["Těsto_Ovoce", "Koláč"],
    ["Hospodářské zvíře_Bláto", "Prase"],
    ["Pták_Město", "Holub"],
    ["Pták_Dopis", "Holub"],
    ["Pták_Socha", "Holub"],
    ["Prase_Peníze", "Kasička"],
    ["Keramika_Prase", "Kasička"],
    ["Bavlna_Tkanina", "Polštář"],
    ["Letadlo_Člověk", "Pilot"],
    ["Tabák_Dřevo", "Trubka"],
    ["Ryba_Krev", "Piraňa"],
    ["Meč_Námořník", "Pirát"],
    ["Námořník_Pirátská loď", "Pirát"],
    ["Plachetnice_Pirát", "Pirátská loď"],
    ["Loď_Pirát", "Pirátská loď"],
    ["Nástroj_Seno", "Vidle"],
    ["Sýr_Těsto", "Pizza"],
    ["Země_Vesmír", "Planeta"],
    ["Déšť_Země", "Rostlina"],
    ["Bobr_Kachna", "Ptakopysk"],
    ["Voda_Zahrada", "Rybník"],
    ["Džus_Led", "Nanuk"],
    ["Oheň_Hlína", "Keramika"],
    ["Hlína_Kolo", "Keramika"],
    ["Hlína_Nástroj", "Keramika"],
    ["Země_Země", "Tlak"],
    ["Sklo_Duha", "Rozklad světla"],
    ["Vzduch_Dinosaurus", "Pterodaktyl"],
    ["Pták_Dinosaurus", "Pterodaktyl"],
    ["Sněhulák_Plamenomet", "Louže"],
    ["Slunce_Led", "Louže"],
    ["Slunce_Sněhulák", "Louže"],
    ["Zelenina_Oheň", "Dýně"],
    ["Zelenina_Světlo", "Dýně"],
    ["Poušť_Kámen", "Pyramida"],
    ["Poušť_Hrob", "Pyramida"],
    ["Písek_Bažina", "Tekutý písek"],
    ["Divoké zvíře_Mrkev", "Králík"],
    ["Voda_Vzduch", "Déšť"],
    ["Déšť_Slunce", "Duha"],
    ["Déšť_Světlo", "Duha"],
    ["Divoké zvíře_Pirátská loď", "Krysa"],
    ["Plachetnice_Divoké zvíře", "Krysa"],
    ["Mouka_Papír", "Recept"],
    ["Papír_Pekař", "Recept"],
    ["Diamant_Kov", "Prsten"],
    ["Diamant_Zlato", "Prsten"],
    ["Hora_Voda", "Řeka"],
    ["Déšť_Hora", "Řeka"],
    ["Kov_Život", "Robot"],
    ["Ocel_Život", "Robot"],
    ["Život_Brnění", "Robot"],
    ["Letadlo_Vesmír", "Raketa"],
    ["Vlákno_Vlákno", "Provaz"],
    ["Láska_Rostlina", "Růže"],
    ["Láska_Květina", "Růže"],
    ["Hrad_Čas", "Ruiny"],
    ["Dům_Čas", "Ruiny"],
    ["Tužka_Dřevo", "Pravítko"],
    ["Kov_Vzduch", "Rez"],
    ["Kyslík_Kov", "Rez"],
    ["Kyslík_Ocel", "Rez"],
    ["Ocel_Vzduch", "Rez"],
    ["Kůže_Kůň", "Sedlo"],
    ["Peníze_Kov", "Sejf"],
    ["Zlato_Kov", "Sejf"],
    ["Peníze_Ocel", "Sejf"],
    ["Zlato_Ocel", "Sejf"],
    ["Dioptrické brýle_Exploze", "Bezpečnostní brýle"],
    ["Dioptrické brýle_Nástroj", "Bezpečnostní brýle"],
    ["Dioptrické brýle_Inženýr", "Bezpečnostní brýle"],
    ["Vítr_Loď", "Plachetnice"],
    ["Tkanina_Loď", "Plachetnice"],
    ["Loď_Člověk", "Námořník"],
    ["Plachetnice_Člověk", "Námořník"],
    ["Slunce_Moře", "Sůl"],
    ["Slunce_Oceán", "Sůl"],
    ["Moře_Oheň", "Sůl"],
    ["Oceán_Oheň", "Sůl"],
    ["Kámen_Vzduch", "Písek"],
    ["Hrad_Písek", "Hrad z písku"],
    ["Energie_Písek", "Písečná bouře"],
    ["Bouře_Písek", "Písečná bouře"],
    ["Hurikán_Písek", "Písečná bouře"],
    ["Šunka_Chléb", "Sendvič"],
    ["Chléb_Sýr", "Sendvič"],
    ["Slanina_Chléb", "Sendvič"],
    ["Vánoční stromeček_Člověk", "Santa"],
    ["Planeta_Prsten", "Saturn"],
    ["Doktor_Čepel", "Skalpel"],
    ["Nemocnice_Čepel", "Skalpel"],
    ["Seno_Člověk", "Strašák"],
    ["Divoké zvíře_Písek", "Škorpion"],
    ["Divoké zvíře_Duny", "Škorpion"],
    ["Čepel_Tráva", "Kosa"],
    ["Čepel_Pšenice", "Kosa"],
    ["Voda_Voda", "Moře"],
    ["Moře_Pták", "Racek"],
    ["Oceán_Pták", "Racek"],
    ["Pláž_Pták", "Racek"],
    ["Moře_Kůň", "Mořský koník"],
    ["Kůň_Oceán", "Mořský koník"],
    ["Kůň_Ryba", "Mořský koník"],
    ["Moře_Pes", "Tuleň"],
    ["Moře_Nemoc", "Mořská nemoc"],
    ["Oceán_Nemoc", "Mořská nemoc"],
    ["Nemoc_Loď", "Mořská nemoc"],
    ["Nemoc_Parník", "Mořská nemoc"],
    ["Nemoc_Plachetnice", "Mořská nemoc"],
    ["Moře_Rostlina", "Chaluha"],
    ["Oceán_Rostlina", "Chaluha"],
    ["Jehla_Elektřina", "Šicí stroj"],
    ["Jehla_Robot", "Šicí stroj"],
    ["Divoké zvíře_Oceán", "Žralok"],
    ["Divoké zvíře_Moře", "Žralok"],
    ["Krev_Moře", "Žralok"],
    ["Oceán_Krev", "Žralok"],
    ["Hospodářské zvíře_Mrak", "Ovce"],
    ["Čepel_Hvězda", "Šuriken"],
    ["Bakterie_Člověk", "Nemoc"],
    ["Nemoc_Člověk", "Nemoc"],
    ["Kolo_Snowboard", "Skateboard"],
    ["Čas_Mrtvola", "Kostra"],
    ["Dioptrické brýle_Sníh", "Lyžařské brýle"],
    ["Vzduch_Mrak", "Obloha"],
    ["Dům_Obloha", "Mrakodrap"],
    ["Kouř_Mlha", "Smog"],
    ["Mlha_Město", "Smog"],
    ["Oheň_Dřevo", "Kouř"],
    ["Táborák_Tkanina", "Kouřový signál"],
    ["Kouř_Tkanina", "Kouřový signál"],
    ["Divoké zvíře_Drát", "Had"],
    ["Pára_Chlad", "Sníh"],
    ["Sníh_Člověk", "Sněhová koule"],
    ["Dřevo_Sníh", "Snowboard"],
    ["Sníh_Surfer", "Snowboard"],
    ["Sníh_Člověk", "Sněhulák"],
    ["Sněhová koule_Sněhová koule", "Sněhulák"],
    ["Mrkev_Sníh", "Sněhulák"],
    ["Mrkev_Sněhová koule", "Sněhulák"],
    ["Popel_Olej", "Mýdlo"],
    ["Mýdlo_Vzduch", "Bublinky"],
    ["Mýdlo_Voda", "Bublinky"],
    ["Oxid uhličitý_Voda", "Sodovka"],
    ["Oxid uhličitý_Džus", "Sodovka"],
    ["Vlna_Vzduch", "Zvuk"],
    ["Hvězda_Obloha", "Vesmír"],
    ["Hvězda_Slunce", "Vesmír"],
    ["Hvězda_Měsíc", "Vesmír"],
    ["Astronaut_Letadlo", "Raketa"],
    ["Dům_Vesmír", "Vesmírná stanice"],
    ["Lev_Člověk", "Sfinga"],
    ["Vlákno_Divoké zvíře", "Pavouk"],
    ["Strom_Myš", "Veverka"],
    ["Noc_Obloha", "Hvězda"],
    ["Teleskop_Noc", "Hvězda"],
    ["Hvězda_Ryba", "Mořská hvězda"],
    ["Hvězda_Moře", "Mořská hvězda"],
    ["Hvězda_Oceán", "Mořská hvězda"],
    ["Nástroj_Kámen", "Socha"],
    ["Medúza_Člověk", "Socha"],
    ["Kráva_Oheň", "Steak"],
    ["Oheň_Voda", "Pára"],
    ["Energie_Voda", "Pára"],
    ["Voda_Parní motor", "Parník"],
    ["Loď_Parní motor", "Parník"],
    ["Nástroj_Bojler", "Parní motor"],
    ["Kolo_Bojler", "Parní motor"],
    ["Uhlí_Kov", "Ocel"],
    ["Doktor_Nástroj", "Stetoskop"],
    ["Láva_Vzduch", "Kámen"],
    ["Mrak_Energie", "Bouře"],
    ["Elektřina_Mrak", "Bouře"],
    ["Táborák_Člověk", "Příběh"],
    ["Energie_Ovoce", "Cukr"],
    ["Oheň_Džus", "Cukr"],
    ["Energie_Džus", "Cukr"],
    ["Obloha_Oheň", "Slunce"],
    ["Slunce_Hodiny", "Sluneční hodiny"],
    ["Slunce_Rostlina", "Slunečnice"],
    ["Slunce_Květina", "Slunečnice"],
    ["Dioptrické brýle_Slunce", "Brýle"],
    ["Dioptrické brýle_Pláž", "Brýle"],
    ["Vlna_Člověk", "Surfer"],
    ["Chaluha_Ryba", "Sushi"],
    ["Chaluha_Kaviár", "Sushi"],
    ["Rostlina_Bláto", "Bažina"],
    ["Tráva_Bláto", "Bažina"],
    ["Nástroj_Ovčí vlna", "Svetr"],
    ["Ovčí vlna_Člověk", "Svetr"],
    ["Voda_Dioptrické brýle", "Plavecké brýle"],
    ["Kov_Čepel", "Meč"],
    ["Ocel_Čepel", "Meč"],
    ["Brnění_Auto", "Tank"],
    ["Zbraň_Auto", "Tank"],
    ["List_Voda", "Čaj"],
    ["Obloha_Sklo", "Teleskop"],
    ["Hvězda_Sklo", "Teleskop"],
    ["Vesmír_Sklo", "Teleskop"],
    ["Tkanina_Dřevo", "Stan"],
    ["Tkanina_Dům", "Stan"],
    ["Nástroj_Bavlna", "Vlákno"],
    ["Ovčí vlna_Kolo", "Vlákno"],
    ["Sklo_Písek", "Čas"],
    ["Ledovec_Parník", "Titanic"],
    ["Oheň_Sendvič", "Toust"],
    ["Oheň_Chléb", "Toust"],
    ["Oheň_Rostlina", "Tabák"],
    ["Člověk_Kov", "Nástroj"],
    ["Duha_Pták", "Tukan"],
    ["Auto_Farmář", "Traktor"],
    ["Auto_Pole", "Traktor"],
    ["Ocel_Parní motor", "Vlak"],
    ["Kov_Parní motor", "Vlak"],
    ["Kolo_Parní motor", "Vlak"],
    ["Vůz_Parní motor", "Vlak"],
    ["Mapa k pokladu_Pirát", "Poklad"],
    ["Mapa_Pirát", "Mapa k pokladu"],
    ["Čas_Rostlina", "Strom"],
    ["Dům_Strom", "Dům na stromě"],
    ["Dřevo_Kůň", "Trojský kůň"],
    ["Zemětřesení_Oceán", "Tsunami"],
    ["Zemětřesení_Moře", "Tsunami"],
    ["Hora_Inženýr", "Tunel"],
    ["Písek_Vajíčko", "Želva"],
    ["Dinosaurus_Maso", "Tyrannosaurus"],
    ["Mimozemšťan_Raketa", "Ufo"],
    ["Mimozemšťan_Letadlo", "Ufo"],
    ["Déšť_Nástroj", "Deštník"],
    ["Tkanina_Déšť", "Deštník"],
    ["Kůň_Duha", "Jednorožec"],
    ["Život_Duha", "Jednorožec"],
    ["Koště_Elektřina", "Vysavač"],
    ["Krev_Člověk", "Upír"],
    ["Upír_Člověk", "Upír"],
    ["Ovoce_Pole", "Zelenina"],
    ["Láva_Země", "Sopka"],
    ["Láva_Hora", "Sopka"],
    ["Oheň_Hora", "Sopka"],
    ["Pták_Mrtvola", "Sup"],
    ["Vozík_Kůň", "Vůz"],
    ["Cihla_Cihla", "Zeď"],
    ["Peníze_Kůže", "Peněženka"],
    ["Dřevo_Čaroděj", "Hůlka"],
    ["Člověk_Meč", "Válečník"],
    ["Hodiny_Člověk", "Hodinky"],
    ["Zbraň_Voda", "Vodní pistolka"],
    ["Rybník_Květina", "Leknín"],
    ["Trubka_Voda", "Vodovodní potrubí"],
    ["Řeka_Hora", "Vodopád"],
    ["Vítr_Oceán", "Vlna"],
    ["Vítr_Moře", "Vlna"],
    ["Úl_Včela", "Vosk"],
    ["Vlákno_Pavouk", "Pavučina"],
    ["Člověk_Vlk", "Vlkodlak"],
    ["Člověk_Vlkodlak", "Vlkodlak"],
    ["Farmář_Pole", "Pšenice"],
    ["Farmář_Rostlina", "Pšenice"],
    ["Dřevo_Nástroj", "Kolo"],
    ["Život_Les", "Divoké zvíře"],
    ["Divoké zvíře_Prase", "Divoké prase"],
    ["Les_Prase", "Divoké prase"],
    ["Vzduch_Tlak", "Vítr"],
    ["Energie_Vzduch", "Vítr"],
    ["Vítr_Dům", "Mlýn"],
    ["Vítr_Kolo", "Mlýn"],
    ["Elektřina_Mlýn", "Větrná turbína"],
    ["Dům_Sklo", "Okno"],
    ["Alkohol_Ovoce", "Víno"],
    ["Kov_Elektřina", "Drát"],
    ["Koště_Člověk", "Čarodějnice"],
    ["Koště_Čaroděj", "Čarodějnice"],
    ["Energie_Člověk", "Čaroděj"],
    ["Les_Pes", "Vlk"],
    ["Měsíc_Divoké zvíře", "Vlk"],
    ["Pes_Divoké zvíře", "Vlk"],
    ["Strom_Nástroj", "Dřevo"],
    ["Nástroj_Ovce", "Ovčí vlna"],
    ["Ovce_Nůžky", "Ovčí vlna"],
    ["Kost_Světlo", "X-ray"],
    ["Kostra_Světlo", "X-ray"],
    ["Bakterie_Mléko", "Jogurt"],
    ["Život_Mrtvola", "Zombie"],
]);