export const TASKS = [
  {
    id: 1,
    title: "Vzestup z popela",
    description: "Legendární opeřenec, který se raději spálí, než by chodil pěšky",
    target: "Fénix",
    reward: 10,
  },
  {
    id: 2,
    title: "Člověk a stroj",
    description: "Neptej se jestli miluje matku, má kovové srdce",
    target: "Kyborg",
    reward: 15,
  },
  {
    id: 3,
    title: "Okřídlený kůň",
    description: "Řecký sprinter s vlastním leteckým průkazem",
    target: "Pegas",
    reward: 15,
  },
  {
    id: 4,
    title: "Vesmírná past",
    description: "Nejlepší dietní plán vesmíru – pohltí úplně všechno",
    target: "Černá díra",
    reward: 10,
  },
  {
    id: 5,
    title: "Prehistorický ninja",
    description: "T-Rex v černém pyžamu a s nindžou v packách",
    target: "Ninjasaurus",
    reward: 30,
  },
  {
    id: 6,
    title: "Věštění budoucnosti",
    description: "Skleněná koule, která vidí tvé ztracené ponožky",
    target: "Krystalová koule",
    reward: 15,
  },
  {
    id: 7,
    title: "Nekonečný život",
    description: "Oživlý jogín bez dechu – hledá mozek k zapůjčení",
    target: "Zombie",
    reward: 20,
  },
  {
    id: 8,
    title: "Strašidelná lucerna",
    description: "Dýně, která si nevzala ponaučení z táboráku",
    target: "Svítící dýně",
    reward: 20,
  },
  {
    id: 9,
    title: "Automatická pomoc",
    description: "Kovový sluha, co tě nahlas počítá do dvojkové soustavy",
    target: "Robot",
    reward: 10,
  },
  {
    id: 10,
    title: "Domov ve hvězdách",
    description: "Nejdražší Airbnb ve vesmíru – výhled na Mléčnou dráhu",
    target: "Vesmírná stanice",
    reward: 5,
  },
  {
    id: 11,
    title: "Ohnivý skladník",
    description: "Létající ještěrka s vášní pro grilování a zlato",
    target: "Drak",
    reward: 15,
  },
  {
    id: 12,
    title: "Pavoučí ateliér",
    description: "Kovový brouk, co šije lépe než tvá babička",
    target: "Šicí stroj",
    reward: 20,
  },
  {
    id: 13,
    title: "Země se potí",
    description: "Přírodní sauna, která občas kýchne kameny",
    target: "Sopka",
    reward: 5,
  },
  {
    id: 14,
    title: "Pichlavý hipster",
    description: "Chodící jehelníček s trvalou nehodou u kadeřníka",
    target: "Ježek",
    reward: 5,
  },
  {
    id: 15,
    title: "Pouštní tank",
    description: "Chodící zásobárna vody",
    target: "Velbloud",
    reward: 10,
  },
  {
    id: 16,
    title: "Měsíční dieta",
    description: "Chlupáč, který jednou za měsíc zapomene na holiče",
    target: "Vlkodlak",
    reward: 20,
  },
  {
    id: 17,
    title: "Geniální okamžik",
    description: "Skleněná bublina, ve které bydlí",
    target: "Žárovka",
    reward: 10,
  },
  {
    id: 18,
    title: "Písečný stratég",
    description: "Pták, co věří, že když nevidí on, nevidí nikdo",
    target: "Pštros",
    reward: 15,
  },
  {
    id: 19,
    title: "Sladké lepivé vězení",
    description: "Ovocné vězení pro chleba",
    target: "Marmeláda",
    reward: 10,
  },
  {
    id: 20,
    title: "Tichá společnost",
    description: "Nejklidnější sousedství, kde nikdo neřeší hluk po 22:00",
    target: "Hřbitov",
    reward: 15,
  },
  {
    id: 21,
    title: "Bažinný módní ikon",
    description: "Kožené brnění s 68 zuby – poslední výkřik bažinové elegance",
    target: "Aligátor",
    reward: 10,
  },
  {
    id: 22,
    title: "Nebeský influencer",
    description: "Létající streamer s křídly a halo efektem – žádné sponzorované hříchy!",
    target: "Anděl",
    reward: 10,
  },
  {
    id: 23,
    title: "Vesmírný tulák",
    description: "Profesionální fotič Země s kamerou za 10 miliard dolarů",
    target: "Astronaut",
    reward: 5,
  },
  {
    id: 24,
    title: "Plynulá zábava",
    description: "Praskavý party element, který nenávidí špendlíky",
    target: "Bublinky",
    reward: 5,
  },
  {
    id: 25,
    title: "Cukrové kouzlo",
    description: "Pruhovaná kouzelnická hůlka s příchutí Vánoc",
    target: "Cukrová hůl",
    reward: 10,
  },
  {
    id: 26,
    title: "Kulatý detektiv",
    description: "Sladký policista s dírou uprostřed – vyšetřuje zmizelé diety",
    target: "Donut",
    reward: 5,
  },
  {
    id: 27,
    title: "Nebeský podvod",
    description: "Optický klam, který slibuje zlato, ale nedá nic",
    target: "Duha",
    reward: 5,
  },
  {
    id: 28,
    title: "Ledové Airbnb",
    description: "Minimalistický dům s výhledem na věčnou zimu – topení není v ceně",
    target: "Iglú",
    reward: 15,
  },
  {
    id: 29,
    title: "Pouštní ninja",
    description: "Zelený samuraj, co tě obejme… ale jen jednou",
    target: "Kaktus",
    reward: 5,
  },
  {
    id: 30,
    title: "Turista z hvězd",
    description: "Ztratil se cestou na záchod – hledá WiFi a lidské chromozomy",
    target: "Mimozemšťan",
    reward: 20,
  },
  {
    id: 31,
    title: "Zahradní požírač",
    description: "Pomalý šéfkuchař, co sní celý salát, než udělá první krok",
    target: "Housenka",
    reward: 10,
  },
  {
    id: 32,
    title: "Květinový žhář",
    description: "Zahradní náčiní pro ty, co chtějí květiny... bez květin",
    target: "Plamenomet",
    reward: 20,
  },
  {
    id: 33,
    title: "Měsíční fanoušek",
    description: "Chlupatý operní pěvec",
    target: "Vlk",
    reward: 5,
  },
  {
    id: 34,
    title: "Ohnivý polštář",
    description: "Sladké uhlíky pro ty, co chtějí cukr s příchutí lesního požáru",
    target: "Marshmallows",
    reward: 5,
  },
  {
    id: 35,
    title: "Pískový filozof",
    description: "Kamenný učitel, co dává testy, ale zapomněl odpovědi",
    target: "Sfinga",
    reward: 20,
  },
  {
    id: 36,
    title: "Mostní šaman",
    description: "Kouzelník s pravítkem'",
    target: "Inženýr",
    reward: 10,
  },
  {
    id: 37,
    title: "Duchovní plavba",
    description: "Plavidlo pro ty, co chtějí plout... i bez moře",
    target: "Pirátská loď",
    reward: 10,
  },
  {
    id: 38,
    title: "Letní terorista",
    description: "Černožlutý gatekeeper, co kontroluje, kdo smí na piknik",
    target: "Včela",
    reward: 5,
  },
  {
    id: 39,
    title: "Kutilův sen",
    description: "Stavebnice pro dospělé: sešij 5 sousedů a přidej blesk!",
    target: "Frankenstein",
    reward: 20,
  },
];
